### ISSUE TITLE
Handle recursive folder structure for multiple upload

### ISSUE THREAD

**Issue by diegantobass** [SciencesPoDRIS/iamassaccess#11]

**Comment by diegantobass** [comment]
The for each file in folder find metadata and upload files

**Comment by annelhote** [comment]
Add use folder's name as item / bucket name.

**Comment by diegantobass** [comment]
Structure of the folder of files to upload should be :
- folder ~= collection:
      - file_1 == item_1:
              - foobar_1.pdf
              - foobar_1.jpg
              - ocr_foobar_1.txt
      - file_2 == item_2:
              - foobar_2.pdf
              - foobar_2.jpg
              - ocr_foobar_2.txt
      - [...]
      - metadata.csv (1 line per file)

**Comment by diegantobass** [comment]
ARE YOU FUCKING KIDDING ME WHERE IS MY INDENTATION?!

**Comment by diegantobass** [comment]
- folder ~= collection
  - file_1 == item_1
    - foobar_1.pdf
    - foobar_1.jpg
    - ocr_foobar_1.txt
    - [...]
  - file_2 == item_2
    - foobar_2.pdf
    - foobar_2.jpg
    - ocr_foobar_2.txt
    - [...]
  - [...]
  - metadata.csv (1 line per file_*)
